### ISSUE TITLE
Lesson 6 - typo and possibly missing reference code

### ISSUE THREAD

**Issue by moonburnt** [ArsThaumaturgis/Panda3DTutorial.io#6] opened 2020-01-20 19:54 UTC
Typo is related to lesson's text itself - at the beginning of "pusher" part, you have additional ',' at the end of import:
`from panda3d.core import CollisionHandlerPusher,`

And missing reference code is about highlights of hitboxes - lesson itself include `collider.show()` and specifically ends with mention about calling .show() on walls too, but reference doesnt include any of these. _Maybe it was intended, coz you've specified that these pieces were there only for debugging purposes - I wasnt 100% sure, thus mentioned it_

**Comment by ArsThaumaturgis** [comment] 2020-01-20 20:11
As to the first, indeed, that comma is erroneous! At a guess, I may have left it in by mistake when copying the import from a longer import-list. ^^; 

That should be fixed now in https://github.com/ArsThaumaturgis/Panda3DTutorial.io/commit/7a00056e27c9aa346cc808a1468d354e66e0d2b4. ^_^

As to the latter, I think that it that was intended simply to show readers how to display their collision objects, and to show the collision objects at the end. Since it was wasn't intended for the final project, I left it out of the reference code.

I do agree that this might be unclear, so I've added a quick note at the end of the lesson that mentions this! It should have been added in https://github.com/ArsThaumaturgis/Panda3DTutorial.io/commit/cef1efbf76475967e63c71754bebb529611eaf9c. ^_^

Thank you very much for these reports, by the way!

**Closed by ArsThaumaturgis** 2020-01-20 20:11 UTC
